/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author acer
 */
public class bajuadat extends javax.swing.JFrame {

    /**
     * Creates new form huruf
     */
    int set=0;
    public bajuadat() {
        initComponents();
        
        btnbefore.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        a1 = new javax.swing.JPanel();
        baju = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a2 = new javax.swing.JPanel();
        baju1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a3 = new javax.swing.JPanel();
        baju2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a4 = new javax.swing.JPanel();
        baju3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        a5 = new javax.swing.JPanel();
        baju4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a6 = new javax.swing.JPanel();
        baju5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        a7 = new javax.swing.JPanel();
        baju6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        a8 = new javax.swing.JPanel();
        baju7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a9 = new javax.swing.JPanel();
        baju8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a10 = new javax.swing.JPanel();
        baju9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        a11 = new javax.swing.JPanel();
        baju10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a12 = new javax.swing.JPanel();
        baju11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a13 = new javax.swing.JPanel();
        baju12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a14 = new javax.swing.JPanel();
        baju13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a15 = new javax.swing.JPanel();
        baju14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a16 = new javax.swing.JPanel();
        baju15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        a17 = new javax.swing.JPanel();
        baju16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        a18 = new javax.swing.JPanel();
        baju17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        a19 = new javax.swing.JPanel();
        baju18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        a20 = new javax.swing.JPanel();
        baju19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        a21 = new javax.swing.JPanel();
        baju20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        a22 = new javax.swing.JPanel();
        baju21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        a23 = new javax.swing.JPanel();
        baju22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        a24 = new javax.swing.JPanel();
        baju23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        a25 = new javax.swing.JPanel();
        baju24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a26 = new javax.swing.JPanel();
        baju25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        a27 = new javax.swing.JPanel();
        baju26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        a28 = new javax.swing.JPanel();
        baju27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        a29 = new javax.swing.JPanel();
        baju28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        a30 = new javax.swing.JPanel();
        baju29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        a31 = new javax.swing.JPanel();
        baju30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        a32 = new javax.swing.JPanel();
        baju31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        a33 = new javax.swing.JPanel();
        baju32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnbefore = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        group.setBorder(null);
        group.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider1.setBorder(null);
        jPanelSlider1.setOpaque(false);

        a1.setOpaque(false);
        a1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a1.add(baju, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a1, "card2");

        a2.setOpaque(false);
        a2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b2.png"))); // NOI18N
        a2.add(baju1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t2.png"))); // NOI18N
        a2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a2, "card2");

        a3.setOpaque(false);
        a3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a3.add(baju2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a3, "card2");

        a4.setOpaque(false);
        a4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a4.add(baju3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a4, "card2");

        a5.setOpaque(false);
        a5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a5.add(baju4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a5, "card2");

        a6.setOpaque(false);
        a6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a6.add(baju5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a6, "card2");

        a7.setOpaque(false);
        a7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a7.add(baju6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a7, "card2");

        a8.setOpaque(false);
        a8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a8.add(baju7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a8, "card2");

        a9.setOpaque(false);
        a9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a9.add(baju8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a9, "card2");

        a10.setOpaque(false);
        a10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a10.add(baju9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a10, "card2");

        a11.setOpaque(false);
        a11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a11.add(baju10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a11, "card2");

        a12.setOpaque(false);
        a12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a12.add(baju11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a12, "card2");

        a13.setOpaque(false);
        a13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a13.add(baju12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a13, "card2");

        a14.setOpaque(false);
        a14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a14.add(baju13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a14, "card2");

        a15.setOpaque(false);
        a15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a15.add(baju14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a15, "card2");

        a16.setOpaque(false);
        a16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a16.add(baju15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a16, "card2");

        a17.setOpaque(false);
        a17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a17.add(baju16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a17, "card2");

        a18.setOpaque(false);
        a18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a18.add(baju17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a18.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a18, "card2");

        a19.setOpaque(false);
        a19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a19.add(baju18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a19, "card2");

        a20.setOpaque(false);
        a20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a20.add(baju19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a20.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a20, "card2");

        a21.setOpaque(false);
        a21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a21.add(baju20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a21.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a21, "card2");

        a22.setOpaque(false);
        a22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a22.add(baju21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a22.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a22, "card2");

        a23.setOpaque(false);
        a23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a23.add(baju22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a23.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a23, "card2");

        a24.setOpaque(false);
        a24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a24.add(baju23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a24.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a24, "card2");

        a25.setOpaque(false);
        a25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a25.add(baju24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a25.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a25, "card2");

        a26.setOpaque(false);
        a26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a26.add(baju25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a26.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a26, "card2");

        a27.setOpaque(false);
        a27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a27.add(baju26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a27.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a27, "card2");

        a28.setOpaque(false);
        a28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a28.add(baju27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a28.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a28, "card2");

        a29.setOpaque(false);
        a29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a29.add(baju28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a29.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a29, "card2");

        a30.setOpaque(false);
        a30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a30.add(baju29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a30.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a30, "card2");

        a31.setOpaque(false);
        a31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a31.add(baju30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a31.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a31, "card2");

        a32.setOpaque(false);
        a32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a32.add(baju31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a32.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a32, "card2");

        a33.setOpaque(false);
        a33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baju32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/b1.png"))); // NOI18N
        a33.add(baju32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 300, 410));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baju/t1.png"))); // NOI18N
        a33.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 537, 57));

        jPanelSlider1.add(a33, "card2");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 550, 580));

        btnbefore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPrev1.png"))); // NOI18N
        btnbefore.setBorderPainted(false);
        btnbefore.setContentAreaFilled(false);
        btnbefore.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPrev1.png"))); // NOI18N
        btnbefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeforeActionPerformed(evt);
            }
        });
        getContentPane().add(btnbefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext1.png"))); // NOI18N
        btnnext.setBorderPainted(false);
        btnnext.setContentAreaFilled(false);
        btnnext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext2.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgroung baju.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeforeActionPerformed
              
    }//GEN-LAST:event_btnbeforeActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        group.nextPanel(50, group, group.left);
        btnbefore.setVisible(true);
        btnnext.setVisible(false);
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainmenu a = new mainmenu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public void kurang(){
switch (set){
    case 0 : group.nextPanel(50, group, group.right); break;
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bajuadat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a1;
    private javax.swing.JPanel a10;
    private javax.swing.JPanel a11;
    private javax.swing.JPanel a12;
    private javax.swing.JPanel a13;
    private javax.swing.JPanel a14;
    private javax.swing.JPanel a15;
    private javax.swing.JPanel a16;
    private javax.swing.JPanel a17;
    private javax.swing.JPanel a18;
    private javax.swing.JPanel a19;
    private javax.swing.JPanel a2;
    private javax.swing.JPanel a20;
    private javax.swing.JPanel a21;
    private javax.swing.JPanel a22;
    private javax.swing.JPanel a23;
    private javax.swing.JPanel a24;
    private javax.swing.JPanel a25;
    private javax.swing.JPanel a26;
    private javax.swing.JPanel a27;
    private javax.swing.JPanel a28;
    private javax.swing.JPanel a29;
    private javax.swing.JPanel a3;
    private javax.swing.JPanel a30;
    private javax.swing.JPanel a31;
    private javax.swing.JPanel a32;
    private javax.swing.JPanel a33;
    private javax.swing.JPanel a4;
    private javax.swing.JPanel a5;
    private javax.swing.JPanel a6;
    private javax.swing.JPanel a7;
    private javax.swing.JPanel a8;
    private javax.swing.JPanel a9;
    private javax.swing.JLabel baju;
    private javax.swing.JLabel baju1;
    private javax.swing.JLabel baju10;
    private javax.swing.JLabel baju11;
    private javax.swing.JLabel baju12;
    private javax.swing.JLabel baju13;
    private javax.swing.JLabel baju14;
    private javax.swing.JLabel baju15;
    private javax.swing.JLabel baju16;
    private javax.swing.JLabel baju17;
    private javax.swing.JLabel baju18;
    private javax.swing.JLabel baju19;
    private javax.swing.JLabel baju2;
    private javax.swing.JLabel baju20;
    private javax.swing.JLabel baju21;
    private javax.swing.JLabel baju22;
    private javax.swing.JLabel baju23;
    private javax.swing.JLabel baju24;
    private javax.swing.JLabel baju25;
    private javax.swing.JLabel baju26;
    private javax.swing.JLabel baju27;
    private javax.swing.JLabel baju28;
    private javax.swing.JLabel baju29;
    private javax.swing.JLabel baju3;
    private javax.swing.JLabel baju30;
    private javax.swing.JLabel baju31;
    private javax.swing.JLabel baju32;
    private javax.swing.JLabel baju4;
    private javax.swing.JLabel baju5;
    private javax.swing.JLabel baju6;
    private javax.swing.JLabel baju7;
    private javax.swing.JLabel baju8;
    private javax.swing.JLabel baju9;
    private javax.swing.JButton btnbefore;
    private javax.swing.JButton btnnext;
    private diu.swe.habib.JPanelSlider.JPanelSlider group;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    // End of variables declaration//GEN-END:variables
}
