/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author acer
 */
public class bajuadat extends javax.swing.JFrame {

    /**
     * Creates new form huruf
     */
    public bajuadat() {
        initComponents();
        btnbefore.setVisible(false);
        btnok.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouphuruf = new diu.swe.habib.JPanelSlider.JPanelSlider();
        group1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        group2 = new javax.swing.JPanel();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        group3 = new javax.swing.JPanel();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        show = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnbefore = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grouphuruf.setOpaque(false);

        group1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setText("1");
        group1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 160));

        b2.setText("2");
        group1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        b3.setText("3");
        group1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        b4.setText("4");
        group1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        b5.setText("5");
        group1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        b6.setText("6");
        group1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        b7.setText("7");
        group1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        b8.setText("8");
        group1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        b9.setText("9");
        group1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        group1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        b11.setText("11");
        group1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        grouphuruf.add(group1, "card2");

        group2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b12.setText("12");
        group2.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 80));

        b13.setText("13");
        group2.add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        b14.setText("14");
        group2.add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        b15.setText("15");
        group2.add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        b18.setText("18");
        group2.add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        b16.setText("16");
        group2.add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        b17.setText("17");
        group2.add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        b19.setText("19");
        group2.add(b19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        b20.setText("20");
        group2.add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        b21.setText("21");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        group2.add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        b22.setText("22");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        group2.add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        grouphuruf.add(group2, "card2");

        group3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b23.setText("23");
        group3.add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 80));

        b24.setText("24");
        group3.add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        b25.setText("25");
        group3.add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        b26.setText("26");
        group3.add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        b27.setText("27");
        group3.add(b27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        b28.setText("28");
        group3.add(b28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        b29.setText("29");
        group3.add(b29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        b30.setText("30");
        group3.add(b30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        b31.setText("31");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        group3.add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        b32.setText("32");
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        group3.add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        b33.setText("33");
        group3.add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        grouphuruf.add(group3, "card2");
        grouphuruf.add(show, "card4");

        getContentPane().add(grouphuruf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 830, 380));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 537, 57));

        btnbefore.setText("before");
        btnbefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeforeActionPerformed(evt);
            }
        });
        getContentPane().add(btnbefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        btnnext.setText("next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        btnok.setText("ok");
        getContentPane().add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgroung baju.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeforeActionPerformed
       grouphuruf.nextPanel(50, group1, grouphuruf.right);
        btnnext.setVisible(true);
        btnbefore.setVisible(false);
        
    }//GEN-LAST:event_btnbeforeActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        grouphuruf.nextPanel(50, group2, grouphuruf.left);
        btnbefore.setVisible(true);
        btnnext.setVisible(false);
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b32ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b22ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b31ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainmenu a = new mainmenu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bajuadat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bajuadat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton btnbefore;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnok;
    private javax.swing.JPanel group1;
    private javax.swing.JPanel group2;
    private javax.swing.JPanel group3;
    private diu.swe.habib.JPanelSlider.JPanelSlider grouphuruf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel show;
    // End of variables declaration//GEN-END:variables
}
