/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author acer
 */
public class bermain_warna_new extends javax.swing.JFrame {

    /**
     * Creates new form soal
     */
    JPanel[] panelarraysoal = new JPanel[50];
    JPanel[] panelarrayjawaban = new JPanel[50];
    JPanel[] panelarrayjawaban2 = new JPanel[50];
    JPanel[] panelarrayjawaban3 = new JPanel[50];
    String[] daftarsoal = new String[50];
    String[] daftarjawaban= new String[50];
    int set = 0;
JPanel setjpanel;
JPanel setjpanelpilih;
    public bermain_warna_new() {
        this.setjpanel = panelbalon;
        this.setjpanelpilih = truk1;
        initComponents();
setpanel();
    }

    public void setpanel() {
        File dir = new File("aset\\warna\\di balon");
        String[] files;
        files = dir.list();
        for (int i = 0; i < 50; i++) {
            panelarraysoal[i] = new JPanel(new CardLayout());
            panelarraysoal[i].setOpaque(false);
            panelarrayjawaban[i] = new JPanel(new CardLayout());
            panelarrayjawaban[i].setOpaque(false);
            panelarrayjawaban2[i] = new JPanel(new CardLayout());
            panelarrayjawaban2[i].setOpaque(false);
            panelarrayjawaban3[i] = new JPanel(new CardLayout());
            panelarrayjawaban3[i].setOpaque(false);
        }
        panelsoal.setLayout(new CardLayout());
        for (int i = 0; i < 50; i++) {
            ImageIcon image = new ImageIcon("aset\\warna\\di balon\\" + files[i]);
            JLabel imagelabel = new JLabel(image);
            panelarraysoal[i].add(imagelabel);
            imagelabel.setHorizontalAlignment(JLabel.CENTER);

            ImageIcon image2 = new ImageIcon("aset\\warna\\di truk\\" + files[i]);
            JLabel imagelabel2 = new JLabel(image2);
            panelarrayjawaban[i].add(imagelabel2);
            panelarrayjawaban2[i].add(imagelabel2);
            panelarrayjawaban3[i].add(imagelabel2);
        }
        for (int i = 0; i < 50; i++) {
            panelsoal.add(panelarraysoal[i]);
            paneljawaban1.add(panelarrayjawaban[i]);
            paneljawaban2.add(panelarrayjawaban2[i]);
            paneljawaban3.add(panelarrayjawaban3[i]);
        }
        random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        panelsoal = new diu.swe.habib.JPanelSlider.JPanelSlider();
        balon = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelbalon1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelbalon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        paneljawaban1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        paneljawaban2 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        paneljawaban3 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        truk = new diu.swe.habib.JPanelSlider.JPanelSlider();
        truk1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        truk2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 130, 140));

        panelsoal.setBorder(null);
        panelsoal.setOpaque(false);
        getContentPane().add(panelsoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 280));

        balon.setBorder(null);
        balon.setOpaque(false);

        panelbalon1.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/balon abu.png"))); // NOI18N
        panelbalon1.add(jLabel3);

        balon.add(panelbalon1, "card3");

        panelbalon.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/balon abu.png"))); // NOI18N
        panelbalon.add(jLabel2);

        balon.add(panelbalon, "card3");

        getContentPane().add(balon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1030, 400));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 300, 100, 230));

        paneljawaban1.setBorder(null);
        paneljawaban1.setOpaque(false);
        getContentPane().add(paneljawaban1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 530, 250));

        paneljawaban2.setBorder(null);
        paneljawaban2.setOpaque(false);
        getContentPane().add(paneljawaban2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 620, 250));

        paneljawaban3.setBorder(null);
        paneljawaban3.setOpaque(false);
        getContentPane().add(paneljawaban3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 580, 250));

        truk.setBorder(null);
        truk.setOpaque(false);

        truk1.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/truk.png"))); // NOI18N
        truk1.add(jLabel4);

        truk.add(truk1, "card3");

        truk2.setOpaque(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/truk.png"))); // NOI18N
        truk2.add(jLabel5);
        truk2.add(jLabel1);

        truk.add(truk2, "card3");

        getContentPane().add(truk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1030, 350));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgbermainwarna.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 1030, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        random();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pilih_warna a = new pilih_warna();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
   public void random(){
   set++;
   int kecepatan=35;
        if (set == 50) {
            set = 0;
        }
        if (setjpanel==panelbalon) {
            setjpanel=panelbalon1;
            setjpanelpilih=truk1;
        }else{
        setjpanel=panelbalon;
        setjpanelpilih=truk2;
        }
        System.out.println("set ke =" + set);
        panelsoal.nextPanel(kecepatan, panelarraysoal[set], panelsoal.left);
        balon.nextPanel(kecepatan, setjpanel, balon.left);
        paneljawaban1.nextPanel(kecepatan, panelarrayjawaban[set], paneljawaban1.right);
        paneljawaban2.nextPanel(kecepatan, panelarrayjawaban2[set], paneljawaban2.right);
        paneljawaban3.nextPanel(kecepatan, panelarrayjawaban3[set], paneljawaban3.right);
        truk.nextPanel(kecepatan, setjpanelpilih, balon.right);
        Musik_Play();
   }
    public void Musik_Play() {
        play a = new play();
        a.start();
    }

    class play extends Thread {

        public void run() {
            try {
                FileInputStream fileInputStream = new FileInputStream("aset\\warna\\wo.mp3");
                Player player = new Player(fileInputStream);
                player.play();
                stop();
                System.out.println("aaaaa");
            } catch (FileNotFoundException e) {
            } catch (JavaLayerException e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bermain_warna_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bermain_warna_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bermain_warna_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bermain_warna_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bermain_warna_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private diu.swe.habib.JPanelSlider.JPanelSlider balon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelbalon;
    private javax.swing.JPanel panelbalon1;
    private diu.swe.habib.JPanelSlider.JPanelSlider paneljawaban1;
    private diu.swe.habib.JPanelSlider.JPanelSlider paneljawaban2;
    private diu.swe.habib.JPanelSlider.JPanelSlider paneljawaban3;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelsoal;
    private diu.swe.habib.JPanelSlider.JPanelSlider truk;
    private javax.swing.JPanel truk1;
    private javax.swing.JPanel truk2;
    // End of variables declaration//GEN-END:variables
}
