/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author acer
 */
public class negara_bendera extends javax.swing.JFrame {

    /**
     * Creates new form negara_bendera
     */
    AudioInputStream audioIn;
    Clip clip;

    public negara_bendera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jLabel1 = new javax.swing.JLabel();
        world = new javax.swing.JPanel();
        btnamerika = new javax.swing.JButton();
        btnasia = new javax.swing.JButton();
        btneropa = new javax.swing.JButton();
        btnafrika = new javax.swing.JButton();
        btnaustralia = new javax.swing.JButton();
        afrika = new javax.swing.JLabel();
        amerika = new javax.swing.JLabel();
        australia = new javax.swing.JLabel();
        eropa = new javax.swing.JLabel();
        asia = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        worlderopa = new javax.swing.JPanel();
        eropatimur = new javax.swing.JButton();
        eropabarat = new javax.swing.JButton();
        eropatengah = new javax.swing.JButton();
        eropaselatan = new javax.swing.JButton();
        eropautara = new javax.swing.JButton();
        worldafrika = new javax.swing.JPanel();
        afrikautara = new javax.swing.JButton();
        afrikatimur = new javax.swing.JButton();
        afrikabarat = new javax.swing.JButton();
        afrikatengah = new javax.swing.JButton();
        afrikaselatan = new javax.swing.JButton();
        worldaustralia = new javax.swing.JPanel();
        worldasia = new javax.swing.JPanel();
        asiatenggara = new javax.swing.JButton();
        asiatimur = new javax.swing.JButton();
        asiabarat = new javax.swing.JButton();
        asiatengah = new javax.swing.JButton();
        asiaselatan = new javax.swing.JButton();
        worldamerika = new javax.swing.JPanel();
        amerikautara = new javax.swing.JButton();
        amerikatengah = new javax.swing.JButton();
        amerikaselatan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelutama.setBorder(null);
        panelutama.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/benua.png"))); // NOI18N
        panelutama.add(jLabel1, "card8");

        world.setOpaque(false);
        world.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnamerika.setBorderPainted(false);
        btnamerika.setContentAreaFilled(false);
        btnamerika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnamerikaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnamerikaMouseExited(evt);
            }
        });
        btnamerika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamerikaActionPerformed(evt);
            }
        });
        world.add(btnamerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 410));

        btnasia.setBorderPainted(false);
        btnasia.setContentAreaFilled(false);
        btnasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnasiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnasiaMouseExited(evt);
            }
        });
        btnasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasiaActionPerformed(evt);
            }
        });
        world.add(btnasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 290, 260));

        btneropa.setBorderPainted(false);
        btneropa.setContentAreaFilled(false);
        btneropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneropaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneropaMouseExited(evt);
            }
        });
        btneropa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneropaActionPerformed(evt);
            }
        });
        world.add(btneropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 120));

        btnafrika.setBorderPainted(false);
        btnafrika.setContentAreaFilled(false);
        btnafrika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnafrikaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnafrikaMouseExited(evt);
            }
        });
        btnafrika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnafrikaActionPerformed(evt);
            }
        });
        world.add(btnafrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, 220));

        btnaustralia.setBorderPainted(false);
        btnaustralia.setContentAreaFilled(false);
        btnaustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaustraliaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaustraliaMouseExited(evt);
            }
        });
        btnaustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaustraliaActionPerformed(evt);
            }
        });
        world.add(btnaustralia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 280, 140));

        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika1.png"))); // NOI18N
        world.add(afrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, 330));

        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika1.png"))); // NOI18N
        world.add(amerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 410, 480));

        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia1.png"))); // NOI18N
        world.add(australia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 270, 210));

        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa1.png"))); // NOI18N
        world.add(eropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 260, 250));

        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia1.png"))); // NOI18N
        world.add(asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 390, 320));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        world.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 100, 100));

        panelutama.add(world, "card2");

        worlderopa.setOpaque(false);
        worlderopa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eropatimur.setText("eropa timur");
        eropatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropatimurActionPerformed(evt);
            }
        });
        worlderopa.add(eropatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, -1));

        eropabarat.setText("eropa barat");
        eropabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropabaratActionPerformed(evt);
            }
        });
        worlderopa.add(eropabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        eropatengah.setText("eropa tengah");
        eropatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropatengahActionPerformed(evt);
            }
        });
        worlderopa.add(eropatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        eropaselatan.setText("eropa selatan");
        eropaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropaselatanActionPerformed(evt);
            }
        });
        worlderopa.add(eropaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        eropautara.setText("eropa utara");
        eropautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropautaraActionPerformed(evt);
            }
        });
        worlderopa.add(eropautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        panelutama.add(worlderopa, "card3");

        worldafrika.setOpaque(false);
        worldafrika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afrikautara.setText("afrika utara");
        afrikautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikautaraActionPerformed(evt);
            }
        });
        worldafrika.add(afrikautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        afrikatimur.setText("afrika timur");
        afrikatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikatimurActionPerformed(evt);
            }
        });
        worldafrika.add(afrikatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        afrikabarat.setText("afrika barat");
        afrikabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikabaratActionPerformed(evt);
            }
        });
        worldafrika.add(afrikabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        afrikatengah.setText("afrika tengah");
        afrikatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikatengahActionPerformed(evt);
            }
        });
        worldafrika.add(afrikatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        afrikaselatan.setText("afrika selatan");
        afrikaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikaselatanActionPerformed(evt);
            }
        });
        worldafrika.add(afrikaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        panelutama.add(worldafrika, "card3");

        worldaustralia.setOpaque(false);
        worldaustralia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelutama.add(worldaustralia, "card3");

        worldasia.setOpaque(false);
        worldasia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asiatenggara.setText("asia tengara");
        asiatenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatenggaraActionPerformed(evt);
            }
        });
        worldasia.add(asiatenggara, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        asiatimur.setText("asia timur");
        asiatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatimurActionPerformed(evt);
            }
        });
        worldasia.add(asiatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        asiabarat.setText("asia barat");
        asiabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiabaratActionPerformed(evt);
            }
        });
        worldasia.add(asiabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        asiatengah.setText("asia tengah");
        asiatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatengahActionPerformed(evt);
            }
        });
        worldasia.add(asiatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        asiaselatan.setText("asia selatan");
        asiaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiaselatanActionPerformed(evt);
            }
        });
        worldasia.add(asiaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        panelutama.add(worldasia, "card3");

        worldamerika.setOpaque(false);
        worldamerika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amerikautara.setText("amerika utara");
        amerikautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikautaraActionPerformed(evt);
            }
        });
        worldamerika.add(amerikautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        amerikatengah.setText("amerika tengah");
        amerikatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikatengahActionPerformed(evt);
            }
        });
        worldamerika.add(amerikatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        amerikaselatan.setText("amerika selatan");
        amerikaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikaselatanActionPerformed(evt);
            }
        });
        worldamerika.add(amerikaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        panelutama.add(worldamerika, "card3");

        getContentPane().add(panelutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneropaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneropaMouseEntered
        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa2.png")));
    }//GEN-LAST:event_btneropaMouseEntered

    private void btneropaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneropaMouseExited
        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa1.png")));
    }//GEN-LAST:event_btneropaMouseExited

    private void btnafrikaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafrikaMouseEntered
        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika2.png")));
    }//GEN-LAST:event_btnafrikaMouseEntered

    private void btnafrikaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafrikaMouseExited
        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika1.png")));
    }//GEN-LAST:event_btnafrikaMouseExited

    private void btnasiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasiaMouseEntered
        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia2.png")));
    }//GEN-LAST:event_btnasiaMouseEntered

    private void btnasiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasiaMouseExited
        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia1.png")));
    }//GEN-LAST:event_btnasiaMouseExited

    private void btnamerikaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnamerikaMouseEntered
        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika2.png")));
    }//GEN-LAST:event_btnamerikaMouseEntered

    private void btnamerikaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnamerikaMouseExited
        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika1.png")));
    }//GEN-LAST:event_btnamerikaMouseExited

    private void btnaustraliaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaustraliaMouseEntered
        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia2.png")));
    }//GEN-LAST:event_btnaustraliaMouseEntered

    private void btnaustraliaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaustraliaMouseExited
        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia1.png")));
    }//GEN-LAST:event_btnaustraliaMouseExited

    //eropa
    private void eropautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropautaraActionPerformed
        setpaneleropa("eropa_utara");

    }//GEN-LAST:event_eropautaraActionPerformed

    private void eropabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropabaratActionPerformed
        setpaneleropa("eropa_barat");
    }//GEN-LAST:event_eropabaratActionPerformed

    private void eropatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropatengahActionPerformed
        setpaneleropa("eropa_tengah");
    }//GEN-LAST:event_eropatengahActionPerformed

    private void eropatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropatimurActionPerformed
        setpaneleropa("eropa_timur");
    }//GEN-LAST:event_eropatimurActionPerformed

    private void eropaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropaselatanActionPerformed
        setpaneleropa("eropa_selatan");
    }//GEN-LAST:event_eropaselatanActionPerformed

    //afrika
    private void afrikautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikautaraActionPerformed
        setpanelafrika("afrika_utara");
    }//GEN-LAST:event_afrikautaraActionPerformed

    private void afrikatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikatengahActionPerformed
        setpanelafrika("afrika_tengah");
    }//GEN-LAST:event_afrikatengahActionPerformed

    private void afrikatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikatimurActionPerformed
        setpanelafrika("afrika_timur");
    }//GEN-LAST:event_afrikatimurActionPerformed

    private void afrikaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikaselatanActionPerformed
        setpanelafrika("afrika_selatan");
    }//GEN-LAST:event_afrikaselatanActionPerformed

    private void afrikabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikabaratActionPerformed
        setpanelafrika("afrika_barat");
    }//GEN-LAST:event_afrikabaratActionPerformed

    //asia
    private void asiabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiabaratActionPerformed
        setpanelasia("asia_barat");
    }//GEN-LAST:event_asiabaratActionPerformed

    private void asiatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatengahActionPerformed
        setpanelasia("asia_tengah");
    }//GEN-LAST:event_asiatengahActionPerformed

    private void asiaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiaselatanActionPerformed
        setpanelasia("asia_selatan");
    }//GEN-LAST:event_asiaselatanActionPerformed

    private void asiatenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatenggaraActionPerformed
        setpanelasia("asia_tenggara");
    }//GEN-LAST:event_asiatenggaraActionPerformed

    private void asiatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatimurActionPerformed
        setpanelasia("asia_timur");
    }//GEN-LAST:event_asiatimurActionPerformed

    private void amerikautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikautaraActionPerformed
        setpanelamerika("amerika_utara");
    }//GEN-LAST:event_amerikautaraActionPerformed

    private void amerikatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikatengahActionPerformed
        setpanelamerika("amerika_tengah");
    }//GEN-LAST:event_amerikatengahActionPerformed

    private void amerikaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikaselatanActionPerformed
        setpanelamerika("amerika_selatan");
    }//GEN-LAST:event_amerikaselatanActionPerformed

    //tombol map
    private void btnamerikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamerikaActionPerformed
        panelutama.nextPanel(20, worldamerika, panelutama.left);
        soundbagianbenua("benua-amerika");
    }//GEN-LAST:event_btnamerikaActionPerformed

    private void btnasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasiaActionPerformed
        panelutama.nextPanel(20, worldasia, panelutama.left);
        soundbagianbenua("benua-asia");
    }//GEN-LAST:event_btnasiaActionPerformed

    private void btnafrikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnafrikaActionPerformed
        panelutama.nextPanel(20, worldafrika, panelutama.left);
        soundbagianbenua("benua-afrika");
    }//GEN-LAST:event_btnafrikaActionPerformed

    private void btnaustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaustraliaActionPerformed
        setpanelaustralia();
        soundbagianbenua("benua-australia");
    }//GEN-LAST:event_btnaustraliaActionPerformed

    private void btneropaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneropaActionPerformed
        panelutama.nextPanel(20, worlderopa, panelutama.left);
        soundbagianbenua("benua-eropa");
    }//GEN-LAST:event_btneropaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
mainmenu a = new mainmenu();
a.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void soundbagianbenua(String nama) {
//        try {
//            audioIn = AudioSystem.getAudioInputStream(new File("aset/bendera_jpg/sound_benua/" + nama + ".wav"));
//
//            clip = AudioSystem.getClip();
//            clip.open(audioIn);
//            clip.loop(0);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
//        }
        
        /////////////////
        try {
			FileInputStream fileInputStream = new FileInputStream("aset/bendera_jpg/sound_benua/" + nama + ".mp3");
			Player player = new Player(fileInputStream);
			System.out.println("Song is playing...");
			player.play();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JavaLayerException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    public void setpanelafrika(String lokasi) {
        String directory = "aset\\bendera_jpg\\afrika\\" + lokasi;
        
        soundbagianbenua(lokasi);
        tampil_bendera a = new tampil_bendera(directory);
        a.setVisible(true);
        this.dispose();
    }

    public void setpanelamerika(String lokasi) {
        String directory = "aset\\bendera_jpg\\amerika\\" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
        this.dispose();
    }

    public void setpanelasia(String lokasi) {
        String directory = "aset\\bendera_jpg\\asia\\" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
        this.dispose();
    }

    public void setpaneleropa(String lokasi) {
        String directory = "aset/bendera_jpg/eropa/" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
        this.dispose();
    }

    public void setpanelaustralia() {
        String directory = "aset\\bendera_jpg\\australia";
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua("australia");
        a.setVisible(true);
        this.dispose();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new negara_bendera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afrika;
    private javax.swing.JButton afrikabarat;
    private javax.swing.JButton afrikaselatan;
    private javax.swing.JButton afrikatengah;
    private javax.swing.JButton afrikatimur;
    private javax.swing.JButton afrikautara;
    private javax.swing.JLabel amerika;
    private javax.swing.JButton amerikaselatan;
    private javax.swing.JButton amerikatengah;
    private javax.swing.JButton amerikautara;
    private javax.swing.JLabel asia;
    private javax.swing.JButton asiabarat;
    private javax.swing.JButton asiaselatan;
    private javax.swing.JButton asiatengah;
    private javax.swing.JButton asiatenggara;
    private javax.swing.JButton asiatimur;
    private javax.swing.JLabel australia;
    private javax.swing.JButton btnafrika;
    private javax.swing.JButton btnamerika;
    private javax.swing.JButton btnasia;
    private javax.swing.JButton btnaustralia;
    private javax.swing.JButton btneropa;
    private javax.swing.JLabel eropa;
    private javax.swing.JButton eropabarat;
    private javax.swing.JButton eropaselatan;
    private javax.swing.JButton eropatengah;
    private javax.swing.JButton eropatimur;
    private javax.swing.JButton eropautara;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelutama;
    private javax.swing.JPanel world;
    private javax.swing.JPanel worldafrika;
    private javax.swing.JPanel worldamerika;
    private javax.swing.JPanel worldasia;
    private javax.swing.JPanel worldaustralia;
    private javax.swing.JPanel worlderopa;
    // End of variables declaration//GEN-END:variables
}
