/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author acer
 */
public class tampil_planet extends javax.swing.JFrame {

    /**
     * Creates new form tampil_planet
     */
    String[] planet = {"Merkurius", "Venus", "Bumi", "Bulan", "Mars", "Yupiter", "Saturnus", "Uranus", "Neptunus"};
    JPanel[] planetbayang1 = new JPanel[9];
    JPanel[] planetbayang2 = new JPanel[9];
    JPanel[] planetfull = new JPanel[9];
    int set;

    public tampil_planet(int setarray) {
        initComponents();
        set=setarray;
        setpanel();
        setplanet(set);
    }

    public void setpanel() {
        for (int i = 0; i < 9; i++) {
            planetbayang1[i] = new JPanel(new CardLayout());
            planetbayang1[i].setOpaque(false);
            planetbayang2[i] = new JPanel(new CardLayout());
            planetbayang2[i].setOpaque(false);
            planetfull[i] = new JPanel(new CardLayout());
            planetfull[i].setOpaque(false);
        }
        panelutama.setLayout(new CardLayout());
        for (int i = 0; i < 9; i++) {
            ImageIcon image = new ImageIcon("aset\\tatasurya\\planet" + planet[i] + ".png");
            JLabel imagelabel = new JLabel(image);
            ImageIcon image2 = new ImageIcon("aset\\tatasurya\\planet" + planet[i] + "Lock.png");
            JLabel imagelabel2 = new JLabel(image2);
            ImageIcon image3 = new ImageIcon("aset\\tatasurya\\planet" + planet[i] + "Lock.png");
            JLabel imagelabel3 = new JLabel(image3);
            planetbayang1[i].add(imagelabel2);
            planetbayang2[i].add(imagelabel3);
            planetfull[i].add(imagelabel);
        }
        for (int i = 0; i < 9; i++) {
            panel1.add(planetbayang1[i]);
            panel3.add(planetbayang2[i]);
            panel2.add(planetfull[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panel1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panel2 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panel3 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelutama = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 396, 260, 360));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 290, 360));

        panel1.setBorder(new javax.swing.border.MatteBorder(null));
        panel1.setOpaque(false);
        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 360));

        panel2.setBorder(new javax.swing.border.MatteBorder(null));
        panel2.setOpaque(false);
        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 480, 360));

        panel3.setBorder(new javax.swing.border.MatteBorder(null));
        panel3.setOpaque(false);
        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 400, 280, 360));

        panelutama.setBorder(null);
        panelutama.setOpaque(false);
        getContentPane().add(panelutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 570, 360));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 140, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgtatasurya.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        set++;
        int total = 8;
        if (set == -1) {
            set = total;
        }
        if (set == 9) {
            set = 0;
        }
        int setkiri = set - 1;
        int setkanan = set + 1;
        if (setkiri == -1) {
            setkiri = 8;
        }
        if (setkiri == 9) {
            setkiri = 0;
        }
        if (setkanan == -1) {
            setkanan = 8;
        }
        if (setkanan == 9) {
            setkanan = 0;
        }
        panel1.nextPanel(25, planetbayang1[setkiri], panel1.left);
        panel3.nextPanel(25, planetbayang2[setkanan], panel3.left);
        panel2.nextPanel(25, planetfull[set], panel2.left);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        set--;
        int total = 8;
        if (set == -1) {
            set = total;
        }
        if (set == 9) {
            set = 0;
        }
        int setkiri = set - 1;
        int setkanan = set + 1;

        if (setkiri == -1) {
            setkiri = 8;
        }
        if (setkiri == 9) {
            setkiri = 0;
        }
        if (setkanan == -1) {
            setkanan = 8;
        }
        if (setkanan == 9) {
            setkanan = 0;
        }

        panel1.nextPanel(25, planetbayang1[setkiri], panel1.right);
        panel3.nextPanel(25, planetbayang2[setkanan], panel3.right);
        panel2.nextPanel(25, planetfull[set], panel2.right);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tata_surya a = new tata_surya();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
public void setplanet(int setarray){
        int setkiri = setarray - 1;
        int setkanan = setarray + 1;

        if (setkiri == -1) {
            setkiri = 8;
        }
        if (setkiri == 9) {
            setkiri = 0;
        }
        if (setkanan == -1) {
            setkanan = 8;
        }
        if (setkanan == 9) {
            setkanan = 0;
        }

        panel1.nextPanel(25, planetbayang1[setkiri], panel1.right);
        panel3.nextPanel(25, planetbayang2[setkanan], panel3.right);
        panel2.nextPanel(25, planetfull[setarray], panel2.right);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampil_planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampil_planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampil_planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampil_planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private diu.swe.habib.JPanelSlider.JPanelSlider panel1;
    private diu.swe.habib.JPanelSlider.JPanelSlider panel2;
    private diu.swe.habib.JPanelSlider.JPanelSlider panel3;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelutama;
    // End of variables declaration//GEN-END:variables
}
