/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajar.view;

/**
 *
 * @author acer
 */
public class angka extends javax.swing.JFrame {

    /**
     * Creates new form huruf
     */
    public angka() {
        initComponents();
        btnbefore.setVisible(false);
        btnok.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouphuruf = new diu.swe.habib.JPanelSlider.JPanelSlider();
        group1 = new javax.swing.JPanel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        c0 = new javax.swing.JButton();
        show = new javax.swing.JPanel();
        btnbefore = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grouphuruf.setBorder(null);
        grouphuruf.setOpaque(false);

        group1.setOpaque(false);
        group1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setText("1");
        group1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 100, 130));

        c2.setText("2");
        group1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, 130));

        c3.setText("3");
        group1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 100, 130));

        c4.setText("4");
        group1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 100, 130));

        c5.setText("5");
        group1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, 130));

        c6.setText("6");
        group1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 100, 130));

        c7.setText("7");
        group1.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, 130));

        c8.setText("8");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        group1.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 100, 130));

        c9.setText("9");
        group1.add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 100, 130));

        c0.setText("0");
        c0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c0ActionPerformed(evt);
            }
        });
        group1.add(c0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 130));

        grouphuruf.add(group1, "card2");

        show.setOpaque(false);
        grouphuruf.add(show, "card4");

        getContentPane().add(grouphuruf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 830, 380));

        btnbefore.setText("before");
        btnbefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeforeActionPerformed(evt);
            }
        });
        getContentPane().add(btnbefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        btnnext.setText("next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        btnok.setText("ok");
        getContentPane().add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background huruf.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeforeActionPerformed
       grouphuruf.nextPanel(50, group1, grouphuruf.right);
        btnnext.setVisible(true);
        btnbefore.setVisible(false);
        
    }//GEN-LAST:event_btnbeforeActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed

    }//GEN-LAST:event_btnnextActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c8ActionPerformed

    private void c0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c0ActionPerformed
        grouphuruf.nextPanel(50, show, grouphuruf.);
    }//GEN-LAST:event_c0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(angka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(angka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(angka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(angka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new angka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbefore;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnok;
    private javax.swing.JButton c0;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JPanel group1;
    private diu.swe.habib.JPanelSlider.JPanelSlider grouphuruf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel show;
    // End of variables declaration//GEN-END:variables
}
