/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajar.view;

/**
 *
 * @author acer
 */
public class huruf extends javax.swing.JFrame {

    /**
     * Creates new form huruf
     */
    public huruf() {
        initComponents();
        btnbefore.setVisible(false);
        btnok.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouphuruf = new diu.swe.habib.JPanelSlider.JPanelSlider();
        group1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        group2 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        show = new javax.swing.JPanel();
        btnbefore = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grouphuruf.setOpaque(false);

        group1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("a");
        group1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 80));

        jButton2.setText("b");
        group1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton3.setText("c");
        group1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jButton4.setText("d");
        group1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jButton5.setText("e");
        group1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        jButton6.setText("f");
        group1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jButton7.setText("g");
        group1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jButton8.setText("h");
        group1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jButton9.setText("i");
        group1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jButton10.setText("j");
        group1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jButton11.setText("k");
        group1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jButton12.setText("l");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        group1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jButton13.setText("m");
        group1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        grouphuruf.add(group1, "card2");

        group2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setText("o");
        group2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton16.setText("p");
        group2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jButton17.setText("q");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        group2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jButton18.setText("r");
        group2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jButton19.setText("s");
        group2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        jButton20.setText("t");
        group2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton21.setText("u");
        group2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jButton22.setText("v");
        group2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jButton23.setText("w");
        group2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jButton24.setText("x");
        group2.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jButton25.setText("y");
        group2.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jButton26.setText("z");
        group2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        jButton14.setText("n");
        group2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        grouphuruf.add(group2, "card2");
        grouphuruf.add(show, "card4");

        getContentPane().add(grouphuruf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 830, 380));

        btnbefore.setText("before");
        btnbefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeforeActionPerformed(evt);
            }
        });
        getContentPane().add(btnbefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        btnnext.setText("next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        btnok.setText("ok");
        getContentPane().add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background huruf.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnbeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeforeActionPerformed
       grouphuruf.nextPanel(50, group1, grouphuruf.right);
        btnnext.setVisible(true);
        btnbefore.setVisible(false);
        
    }//GEN-LAST:event_btnbeforeActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        grouphuruf.nextPanel(50, group2, grouphuruf.left);
        btnbefore.setVisible(true);
        btnnext.setVisible(false);
        
    }//GEN-LAST:event_btnnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(huruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(huruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(huruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(huruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new huruf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbefore;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnok;
    private javax.swing.JPanel group1;
    private javax.swing.JPanel group2;
    private diu.swe.habib.JPanelSlider.JPanelSlider grouphuruf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel show;
    // End of variables declaration//GEN-END:variables
}
