/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author acer
 */
public class bermainwarna extends javax.swing.JFrame {

    /**
     * Creates new form bermainwarna
     */
    JPanel[] panelarraysoal = new JPanel[50];
    JPanel[] panelarrayjawaban = new JPanel[50];
    String[] daftarsoal = new String[50];
    String[] daftarjawaban = new String[50];
    int set = 0;
    JPanel setjpanel;
    JPanel setjpanelpilih;
    String benar;
    String[] pilihan = new String[3];
    int poin = 0;
    int counter = 0;
    boolean isIt = true;
    int nyawa = 3;
    boolean close = false;

    public bermainwarna() {
        this.setjpanel = panelbalon2;
        this.setjpanelpilih = truk1;
        initComponents();
        setpanel();
    setcursor();
    }
private void setcursor() {
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    Image cursorImage = toolkit.getImage("cursor.png");
    Point cursorHotSpot = new Point(0,0);
    Cursor customCursor = toolkit.createCustomCursor(cursorImage, cursorHotSpot, "Cursor");
    this.setCursor(customCursor);
    }
    public void setpanel() {
        File dir = new File("src\\di_balon");
        String[] files;
        files = dir.list();
        daftarsoal = files;
        random();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        boxpoin = new javax.swing.JLabel();
        boxnyawa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        balon = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelbalon2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelbalon1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        truk = new diu.swe.habib.JPanelSlider.JPanelSlider();
        truk1 = new javax.swing.JPanel();
        pil3 = new javax.swing.JButton();
        pil1 = new javax.swing.JButton();
        pil2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        truk2 = new javax.swing.JPanel();
        pil4 = new javax.swing.JButton();
        pil5 = new javax.swing.JButton();
        pil6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 130, 140));

        boxpoin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        boxpoin.setForeground(new java.awt.Color(255, 255, 0));
        boxpoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boxpoin.setText("0");
        getContentPane().add(boxpoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, 40));

        boxnyawa.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        boxnyawa.setForeground(new java.awt.Color(255, 0, 0));
        boxnyawa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boxnyawa.setText("3");
        boxnyawa.setToolTipText("");
        boxnyawa.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        getContentPane().add(boxnyawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonNext2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 90, 160));

        balon.setBorder(null);
        balon.setOpaque(false);

        panelbalon2.setOpaque(false);
        panelbalon2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelbalon2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 267, 271));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/balon abu.png"))); // NOI18N
        panelbalon2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 5, -1, -1));

        balon.add(panelbalon2, "card3");

        panelbalon1.setOpaque(false);
        panelbalon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelbalon1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 267, 271));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/balon abu.png"))); // NOI18N
        panelbalon1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 5, -1, -1));

        balon.add(panelbalon1, "card3");

        getContentPane().add(balon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1030, 400));

        truk.setBorder(null);
        truk.setOpaque(false);

        truk1.setOpaque(false);
        truk1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pil3.setBorderPainted(false);
        pil3.setContentAreaFilled(false);
        pil3.setFocusPainted(false);
        pil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil3ActionPerformed(evt);
            }
        });
        truk1.add(pil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 190, 220));

        pil1.setBorderPainted(false);
        pil1.setContentAreaFilled(false);
        pil1.setFocusPainted(false);
        pil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil1ActionPerformed(evt);
            }
        });
        truk1.add(pil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, 220));

        pil2.setBorderPainted(false);
        pil2.setContentAreaFilled(false);
        pil2.setFocusPainted(false);
        pil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil2ActionPerformed(evt);
            }
        });
        truk1.add(pil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/truk.png"))); // NOI18N
        truk1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 5, -1, -1));

        truk.add(truk1, "card3");

        truk2.setOpaque(false);
        truk2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pil4.setBorderPainted(false);
        pil4.setContentAreaFilled(false);
        pil4.setFocusPainted(false);
        pil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil4ActionPerformed(evt);
            }
        });
        truk2.add(pil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, 220));

        pil5.setBorderPainted(false);
        pil5.setContentAreaFilled(false);
        pil5.setFocusPainted(false);
        pil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil5ActionPerformed(evt);
            }
        });
        truk2.add(pil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 220));

        pil6.setBorderPainted(false);
        pil6.setContentAreaFilled(false);
        pil6.setFocusPainted(false);
        pil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil6ActionPerformed(evt);
            }
        });
        truk2.add(pil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 190, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/truk.png"))); // NOI18N
        truk2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 5, -1, -1));

        truk.add(truk2, "card3");

        getContentPane().add(truk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1030, 350));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgbermainwarna.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1030, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        random();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil1ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[0])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil1ActionPerformed

    private void pil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil2ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[1])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil2ActionPerformed

    private void pil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil3ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[2])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil3ActionPerformed

    private void pil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil6ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[2])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil6ActionPerformed

    private void pil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil5ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[1])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil5ActionPerformed

    private void pil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil4ActionPerformed
        popup_benarsalah popup = new popup_benarsalah();
        if (benar.equalsIgnoreCase(pilihan[0])) {
            poin += 5;
            boxpoin.setText(poin + "");
            popup.seticonbenar();
            play a = new play("benar");
            a.start();
        } else {
            popup.seticonsalah();
            play a = new play("salah");
            a.start();
            nyawa--;
        }
        random();
    }//GEN-LAST:event_pil4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (close == true) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (close == true) {
            this.dispose();
        }
    }//GEN-LAST:event_formMouseClicked

    public void random() {

        Random rand = new Random();
        int getrandomsoal = rand.nextInt(49);
        int[] getrandom = getRandom(getrandomsoal);
        benar = daftarsoal[getrandomsoal].charAt(0) + "";
        int pilihsoal = 3;
        if (benar.equalsIgnoreCase("k")) {
            pilihsoal = 0;
        }
        if (benar.equalsIgnoreCase("o")) {
            pilihsoal = 1;
        }
        if (benar.equalsIgnoreCase("c")) {
            pilihsoal = 2;
        }
        if (benar.equalsIgnoreCase("d")) {
            pilihsoal = 3;
        }
        if (benar.equalsIgnoreCase("m")) {
            pilihsoal = 4;
        }
        if (benar.equalsIgnoreCase("h")) {
            pilihsoal = 5;
        }
        if (benar.equalsIgnoreCase("a")) {
            pilihsoal = 6;
        }
        if (benar.equalsIgnoreCase("p")) {
            pilihsoal = 7;
        }
        if (benar.equalsIgnoreCase("b")) {
            pilihsoal = 8;
        }
        if (benar.equalsIgnoreCase("u")) {
            pilihsoal = 9;
        }
        playsoal playsoal = new playsoal(pilihsoal);
        playsoal.start();
        set++;
        int kecepatan = 35;
        if (nyawa < 0) {
            popupscore a = new popupscore("" + poin);
            a.setVisible(true);
        } else {
            boxnyawa.setText("" + nyawa);
            if (set == 50) {
                set = 0;
            }
            if (setjpanel == panelbalon2) {
                seticonpilih(pil1, daftarsoal[getrandom[0]]);
                seticonpilih(pil2, daftarsoal[getrandom[1]]);
                seticonpilih(pil3, daftarsoal[getrandom[2]]);

                seticonsoal(label1, daftarsoal[getrandomsoal]);
                setjpanel = panelbalon1;
                setjpanelpilih = truk1;

            } else {
                seticonpilih(pil4, daftarsoal[getrandom[0]]);
                seticonpilih(pil5, daftarsoal[getrandom[1]]);
                seticonpilih(pil6, daftarsoal[getrandom[2]]);
                seticonsoal(label2, daftarsoal[getrandomsoal]);
                setjpanel = panelbalon2;
                setjpanelpilih = truk2;
            }

            pilihan[0] = daftarsoal[getrandom[0]].charAt(0) + "";
            pilihan[1] = daftarsoal[getrandom[1]].charAt(0) + "";
            pilihan[2] = daftarsoal[getrandom[2]].charAt(0) + "";

            balon.nextPanel(kecepatan, setjpanel, balon.left);
            truk.nextPanel(kecepatan, setjpanelpilih, balon.right);
        }
    }

    public int[] getRandom(int get) {
        int kelipatanke = 0;
        int cek = 0;
        while (true) {
            if (cek <= get) {
                kelipatanke++;
                cek += 5;
            } else {
                break;
            }
        }
        int[] a = new int[3];
        ArrayList<Integer> Nilai_Random = new ArrayList<>();
        int nilai;
        Random randomnya = new Random();
        int dapatmax = kelipatanke * 5;
        int getbenar = (int) (Math.floor(Math.random() * (dapatmax - (dapatmax - 5) + 1)) + (dapatmax - 5));
        if (getbenar == 50) {
            getbenar = 49;
        }
        while (Nilai_Random.size() < 3) {
            boolean sama = false;
            nilai = randomnya.nextInt(49);
            if (Nilai_Random.size() > 0) {
                for (int j = 0; j < Nilai_Random.size(); j++) {
                    if (nilai == Nilai_Random.get(j)) {
                        sama = true;
                        break;
                    }
                }
                if (sama == false) {
                    Nilai_Random.add(nilai);
                }
            } else {
                Nilai_Random.add(nilai);
            }
        }
        for (int j = 0; j < Nilai_Random.size(); j++) {
            a[j] = Nilai_Random.get(j).intValue();
        }
        int indexke = randomnya.nextInt(3);
        a[indexke] = getbenar;
        return a;
    }

    public void seticonpilih(JButton a, String gambar) {
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di_truk/" + gambar)));
    }

    public void seticonsoal(JLabel a, String gambar) {
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di_balon/" + gambar)));
    }

    class playsoal extends Thread {

        int warna;

        public playsoal(int warna) {
            this.warna = warna;
        }

        public void run() {
            try {
                Thread.sleep(1000);
                FileInputStream fileInputStream2 = new FileInputStream("aset\\warna\\pilihwarna.mp3");
                Player player2 = new Player(fileInputStream2);
                player2.play();
                FileInputStream fileInputStream = new FileInputStream("aset\\warna\\w" + warna + ".mp3");
                Player player = new Player(fileInputStream);
                player.play();
                this.stop();
            } catch (JavaLayerException ex) {
                Logger.getLogger(tampil_planet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(bermainwarna.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    class play extends Thread {

        String status;

        public play(String stat) {
            this.status = stat;
        }

        public void run() {
            try {
                if (status.equalsIgnoreCase("benar")) {
                    Random rand = new Random();
                    int getrandom = rand.nextInt(3);
                    FileInputStream fileInputStream = new FileInputStream("aset\\warna\\benar" + (getrandom + 1) + ".mp3");
                    Player player = new Player(fileInputStream);
                    player.play();
                    stop();
                } else {
                    FileInputStream fileInputStream = new FileInputStream("aset\\warna\\salah.mp3");

                    Player player = new Player(fileInputStream);
                    player.play();
                    stop();
                }

            } catch (FileNotFoundException e) {
            } catch (JavaLayerException e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bermainwarna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bermainwarna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bermainwarna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bermainwarna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bermainwarna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private diu.swe.habib.JPanelSlider.JPanelSlider balon;
    private javax.swing.JLabel boxnyawa;
    private javax.swing.JLabel boxpoin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JPanel panelbalon1;
    private javax.swing.JPanel panelbalon2;
    private javax.swing.JButton pil1;
    private javax.swing.JButton pil2;
    private javax.swing.JButton pil3;
    private javax.swing.JButton pil4;
    private javax.swing.JButton pil5;
    private javax.swing.JButton pil6;
    private diu.swe.habib.JPanelSlider.JPanelSlider truk;
    private javax.swing.JPanel truk1;
    private javax.swing.JPanel truk2;
    // End of variables declaration//GEN-END:variables
}
