/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author acer
 */
public class negara_bendera extends javax.swing.JFrame {

    /**
     * Creates new form negara_bendera
     */

    playbacksound a = new playbacksound();
    

    public negara_bendera() {
        initComponents();
        a.start();
   setcursor();
    }
private void setcursor() {
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    Image cursorImage = toolkit.getImage("cursor.png");
    Point cursorHotSpot = new Point(0,0);
    Cursor customCursor = toolkit.createCustomCursor(cursorImage, cursorHotSpot, "Cursor");
    this.setCursor(customCursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new diu.swe.habib.JPanelSlider.JPanelSlider();
        world = new javax.swing.JPanel();
        btnamerika = new javax.swing.JButton();
        btnasia = new javax.swing.JButton();
        btneropa = new javax.swing.JButton();
        btnafrika = new javax.swing.JButton();
        btnaustralia = new javax.swing.JButton();
        afrika = new javax.swing.JLabel();
        amerika = new javax.swing.JLabel();
        australia = new javax.swing.JLabel();
        eropa = new javax.swing.JLabel();
        asia = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        worlderopa = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eropatimur = new javax.swing.JButton();
        eropabarat = new javax.swing.JButton();
        eropatengah = new javax.swing.JButton();
        eropaselatan = new javax.swing.JButton();
        eropautara = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        worldafrika = new javax.swing.JPanel();
        back1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        afrikautara = new javax.swing.JButton();
        afrikatimur = new javax.swing.JButton();
        afrikabarat = new javax.swing.JButton();
        afrikatengah = new javax.swing.JButton();
        afrikaselatan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        worldasia = new javax.swing.JPanel();
        back2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        asiatenggara = new javax.swing.JButton();
        asiatimur = new javax.swing.JButton();
        asiabarat = new javax.swing.JButton();
        asiatengah = new javax.swing.JButton();
        asiaselatan = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        worldamerika = new javax.swing.JPanel();
        back3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        amerikautara = new javax.swing.JButton();
        amerikatengah = new javax.swing.JButton();
        amerikaselatan = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelutama.setBorder(null);
        panelutama.setOpaque(false);

        world.setOpaque(false);
        world.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnamerika.setBorderPainted(false);
        btnamerika.setContentAreaFilled(false);
        btnamerika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnamerikaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnamerikaMouseExited(evt);
            }
        });
        btnamerika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamerikaActionPerformed(evt);
            }
        });
        world.add(btnamerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 410));

        btnasia.setBorderPainted(false);
        btnasia.setContentAreaFilled(false);
        btnasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnasiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnasiaMouseExited(evt);
            }
        });
        btnasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasiaActionPerformed(evt);
            }
        });
        world.add(btnasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 290, 260));

        btneropa.setBorderPainted(false);
        btneropa.setContentAreaFilled(false);
        btneropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneropaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneropaMouseExited(evt);
            }
        });
        btneropa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneropaActionPerformed(evt);
            }
        });
        world.add(btneropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 120));

        btnafrika.setBorderPainted(false);
        btnafrika.setContentAreaFilled(false);
        btnafrika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnafrikaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnafrikaMouseExited(evt);
            }
        });
        btnafrika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnafrikaActionPerformed(evt);
            }
        });
        world.add(btnafrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, 220));

        btnaustralia.setBorderPainted(false);
        btnaustralia.setContentAreaFilled(false);
        btnaustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaustraliaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaustraliaMouseExited(evt);
            }
        });
        btnaustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaustraliaActionPerformed(evt);
            }
        });
        world.add(btnaustralia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 280, 140));

        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika1.png"))); // NOI18N
        world.add(afrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, 330));

        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika1.png"))); // NOI18N
        world.add(amerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 410, 480));

        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia1.png"))); // NOI18N
        world.add(australia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 270, 210));

        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa1.png"))); // NOI18N
        world.add(eropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 260, 250));

        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia1.png"))); // NOI18N
        world.add(asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 390, 320));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonHome2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        world.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/benua.png"))); // NOI18N
        world.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1020, 770));

        panelutama.add(world, "card2");

        worlderopa.setOpaque(false);
        worlderopa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        worlderopa.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 0, 130, 130));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eropa Barat");
        worlderopa.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 280, 100));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eropa Tengah");
        worlderopa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 340, 100));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Eropa Selatan");
        worlderopa.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 340, 100));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Eropa Timur");
        worlderopa.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 310, 100));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eropa Utara");
        worlderopa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 280, 100));

        eropatimur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        eropatimur.setBorderPainted(false);
        eropatimur.setContentAreaFilled(false);
        eropatimur.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        eropatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropatimurActionPerformed(evt);
            }
        });
        worlderopa.add(eropatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 780, 90));

        eropabarat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        eropabarat.setBorderPainted(false);
        eropabarat.setContentAreaFilled(false);
        eropabarat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        eropabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropabaratActionPerformed(evt);
            }
        });
        worlderopa.add(eropabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 750, 110));

        eropatengah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        eropatengah.setBorderPainted(false);
        eropatengah.setContentAreaFilled(false);
        eropatengah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        eropatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropatengahActionPerformed(evt);
            }
        });
        worlderopa.add(eropatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 750, 90));

        eropaselatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        eropaselatan.setBorderPainted(false);
        eropaselatan.setContentAreaFilled(false);
        eropaselatan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        eropaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropaselatanActionPerformed(evt);
            }
        });
        worlderopa.add(eropaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 730, 90));

        eropautara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        eropautara.setBorderPainted(false);
        eropautara.setContentAreaFilled(false);
        eropautara.setFocusPainted(false);
        eropautara.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        eropautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eropautaraActionPerformed(evt);
            }
        });
        worlderopa.add(eropautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 750, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgpilihbagiannegara.png"))); // NOI18N
        worlderopa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 768));

        panelutama.add(worlderopa, "card3");

        worldafrika.setOpaque(false);
        worldafrika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        back1.setBorderPainted(false);
        back1.setContentAreaFilled(false);
        back1.setFocusPainted(false);
        back1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        worldafrika.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 0, 130, 130));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Afrika Utara");
        worldafrika.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 280, 100));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Afrika Timur");
        worldafrika.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 310, 100));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Afrika Selatan");
        worldafrika.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 340, 100));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Afrika Barat");
        worldafrika.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 340, 100));

        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Afrika Tengah");
        worldafrika.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 330, 100));

        afrikautara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        afrikautara.setToolTipText("");
        afrikautara.setBorderPainted(false);
        afrikautara.setContentAreaFilled(false);
        afrikautara.setFocusPainted(false);
        afrikautara.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        afrikautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikautaraActionPerformed(evt);
            }
        });
        worldafrika.add(afrikautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 710, 130));

        afrikatimur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        afrikatimur.setBorderPainted(false);
        afrikatimur.setContentAreaFilled(false);
        afrikatimur.setFocusPainted(false);
        afrikatimur.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        afrikatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikatimurActionPerformed(evt);
            }
        });
        worldafrika.add(afrikatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        afrikabarat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        afrikabarat.setBorderPainted(false);
        afrikabarat.setContentAreaFilled(false);
        afrikabarat.setDefaultCapable(false);
        afrikabarat.setFocusPainted(false);
        afrikabarat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        afrikabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikabaratActionPerformed(evt);
            }
        });
        worldafrika.add(afrikabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        afrikatengah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        afrikatengah.setBorderPainted(false);
        afrikatengah.setContentAreaFilled(false);
        afrikatengah.setFocusPainted(false);
        afrikatengah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        afrikatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikatengahActionPerformed(evt);
            }
        });
        worldafrika.add(afrikatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        afrikaselatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        afrikaselatan.setBorderPainted(false);
        afrikaselatan.setContentAreaFilled(false);
        afrikaselatan.setDefaultCapable(false);
        afrikaselatan.setFocusPainted(false);
        afrikaselatan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        afrikaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afrikaselatanActionPerformed(evt);
            }
        });
        worldafrika.add(afrikaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgpilihbagiannegara.png"))); // NOI18N
        worldafrika.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 768));

        panelutama.add(worldafrika, "card3");

        worldasia.setOpaque(false);
        worldasia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        back2.setBorderPainted(false);
        back2.setContentAreaFilled(false);
        back2.setFocusPainted(false);
        back2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });
        worldasia.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 0, 130, 130));

        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Asia Timur");
        worldasia.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 280, 100));

        jLabel15.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Asia Selatan");
        worldasia.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 340, 100));

        jLabel16.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Asia Tengara");
        worldasia.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 340, 100));

        jLabel17.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Asia Barat");
        worldasia.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 310, 100));

        jLabel18.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Asia Tengah");
        worldasia.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 280, 100));

        asiatenggara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        asiatenggara.setBorderPainted(false);
        asiatenggara.setContentAreaFilled(false);
        asiatenggara.setFocusPainted(false);
        asiatenggara.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        asiatenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatenggaraActionPerformed(evt);
            }
        });
        worldasia.add(asiatenggara, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        asiatimur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        asiatimur.setToolTipText("");
        asiatimur.setBorderPainted(false);
        asiatimur.setContentAreaFilled(false);
        asiatimur.setFocusPainted(false);
        asiatimur.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        asiatimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatimurActionPerformed(evt);
            }
        });
        worldasia.add(asiatimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        asiabarat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        asiabarat.setBorderPainted(false);
        asiabarat.setContentAreaFilled(false);
        asiabarat.setFocusPainted(false);
        asiabarat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        asiabarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiabaratActionPerformed(evt);
            }
        });
        worldasia.add(asiabarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, -1, -1));

        asiatengah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        asiatengah.setBorderPainted(false);
        asiatengah.setContentAreaFilled(false);
        asiatengah.setFocusPainted(false);
        asiatengah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        asiatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiatengahActionPerformed(evt);
            }
        });
        worldasia.add(asiatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        asiaselatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        asiaselatan.setBorderPainted(false);
        asiaselatan.setContentAreaFilled(false);
        asiaselatan.setFocusPainted(false);
        asiaselatan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        asiaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiaselatanActionPerformed(evt);
            }
        });
        worldasia.add(asiaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgpilihbagiannegara.png"))); // NOI18N
        worldasia.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 768));

        panelutama.add(worldasia, "card3");

        worldamerika.setOpaque(false);
        worldamerika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back.png"))); // NOI18N
        back3.setBorderPainted(false);
        back3.setContentAreaFilled(false);
        back3.setFocusPainted(false);
        back3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_back2.png"))); // NOI18N
        back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ActionPerformed(evt);
            }
        });
        worldamerika.add(back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 0, 130, 130));

        jLabel20.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Amerika Tengah");
        worldamerika.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 410, 100));

        jLabel21.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Amerika Selatan");
        worldamerika.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 390, 100));

        jLabel24.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Amerika Utara");
        worldamerika.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 360, 100));

        amerikautara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        amerikautara.setBorderPainted(false);
        amerikautara.setContentAreaFilled(false);
        amerikautara.setFocusPainted(false);
        amerikautara.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        amerikautara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikautaraActionPerformed(evt);
            }
        });
        worldamerika.add(amerikautara, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        amerikatengah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        amerikatengah.setBorderPainted(false);
        amerikatengah.setContentAreaFilled(false);
        amerikatengah.setFocusPainted(false);
        amerikatengah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        amerikatengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikatengahActionPerformed(evt);
            }
        });
        worldamerika.add(amerikatengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        amerikaselatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu1.png"))); // NOI18N
        amerikaselatan.setBorderPainted(false);
        amerikaselatan.setContentAreaFilled(false);
        amerikaselatan.setFocusPainted(false);
        amerikaselatan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kayu2.png"))); // NOI18N
        amerikaselatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amerikaselatanActionPerformed(evt);
            }
        });
        worldamerika.add(amerikaselatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgpilihbagiannegara.png"))); // NOI18N
        worldamerika.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 768));

        panelutama.add(worldamerika, "card3");

        getContentPane().add(panelutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneropaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneropaMouseEntered
        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa2.png")));
    }//GEN-LAST:event_btneropaMouseEntered

    private void btneropaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneropaMouseExited
        eropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaEropa1.png")));
    }//GEN-LAST:event_btneropaMouseExited

    private void btnafrikaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafrikaMouseEntered
        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika2.png")));
    }//GEN-LAST:event_btnafrikaMouseEntered

    private void btnafrikaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafrikaMouseExited
        afrika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAfrika1.png")));
    }//GEN-LAST:event_btnafrikaMouseExited

    private void btnasiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasiaMouseEntered
        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia2.png")));
    }//GEN-LAST:event_btnasiaMouseEntered

    private void btnasiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasiaMouseExited
        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAsia1.png")));
    }//GEN-LAST:event_btnasiaMouseExited

    private void btnamerikaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnamerikaMouseEntered
        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika2.png")));
    }//GEN-LAST:event_btnamerikaMouseEntered

    private void btnamerikaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnamerikaMouseExited
        amerika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAmerika1.png")));
    }//GEN-LAST:event_btnamerikaMouseExited

    private void btnaustraliaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaustraliaMouseEntered
        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia2.png")));
    }//GEN-LAST:event_btnaustraliaMouseEntered

    private void btnaustraliaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaustraliaMouseExited
        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonBenuaAustralia1.png")));
    }//GEN-LAST:event_btnaustraliaMouseExited

    //eropa
    private void eropautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropautaraActionPerformed
        setpaneleropa("eropa_utara");

    }//GEN-LAST:event_eropautaraActionPerformed

    private void eropabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropabaratActionPerformed
        setpaneleropa("eropa_barat");
    }//GEN-LAST:event_eropabaratActionPerformed

    private void eropatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropatengahActionPerformed
        setpaneleropa("eropa_tengah");
    }//GEN-LAST:event_eropatengahActionPerformed

    private void eropatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropatimurActionPerformed
        setpaneleropa("eropa_timur");
    }//GEN-LAST:event_eropatimurActionPerformed

    private void eropaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eropaselatanActionPerformed
        setpaneleropa("eropa_selatan");
    }//GEN-LAST:event_eropaselatanActionPerformed

    //afrika
    private void afrikautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikautaraActionPerformed
        setpanelafrika("afrika_utara");
    }//GEN-LAST:event_afrikautaraActionPerformed

    private void afrikatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikatengahActionPerformed
        setpanelafrika("afrika_tengah");
    }//GEN-LAST:event_afrikatengahActionPerformed

    private void afrikatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikatimurActionPerformed
        setpanelafrika("afrika_timur");
    }//GEN-LAST:event_afrikatimurActionPerformed

    private void afrikaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikaselatanActionPerformed
        setpanelafrika("afrika_selatan");
    }//GEN-LAST:event_afrikaselatanActionPerformed

    private void afrikabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afrikabaratActionPerformed
        setpanelafrika("afrika_barat");
    }//GEN-LAST:event_afrikabaratActionPerformed

    //asia
    private void asiabaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiabaratActionPerformed
        setpanelasia("asia_barat");
    }//GEN-LAST:event_asiabaratActionPerformed

    private void asiatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatengahActionPerformed
        setpanelasia("asia_tengah");
    }//GEN-LAST:event_asiatengahActionPerformed

    private void asiaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiaselatanActionPerformed
        setpanelasia("asia_selatan");
    }//GEN-LAST:event_asiaselatanActionPerformed

    private void asiatenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatenggaraActionPerformed
        setpanelasia("asia_tenggara");
    }//GEN-LAST:event_asiatenggaraActionPerformed

    private void asiatimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiatimurActionPerformed
        setpanelasia("asia_timur");
    }//GEN-LAST:event_asiatimurActionPerformed

    private void amerikautaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikautaraActionPerformed
        setpanelamerika("amerika_utara");
    }//GEN-LAST:event_amerikautaraActionPerformed

    private void amerikatengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikatengahActionPerformed
        setpanelamerika("amerika_tengah");
    }//GEN-LAST:event_amerikatengahActionPerformed

    private void amerikaselatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amerikaselatanActionPerformed
        setpanelamerika("amerika_selatan");
    }//GEN-LAST:event_amerikaselatanActionPerformed

    //tombol map
    private void btnamerikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamerikaActionPerformed
        panelutama.nextPanel(20, worldamerika, panelutama.left);
        soundbagianbenua("benua-amerika");
    }//GEN-LAST:event_btnamerikaActionPerformed

    private void btnasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasiaActionPerformed
        panelutama.nextPanel(20, worldasia, panelutama.left);
        soundbagianbenua("benua-asia");
    }//GEN-LAST:event_btnasiaActionPerformed

    private void btnafrikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnafrikaActionPerformed
        panelutama.nextPanel(20, worldafrika, panelutama.left);
        soundbagianbenua("benua-afrika");
    }//GEN-LAST:event_btnafrikaActionPerformed

    private void btnaustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaustraliaActionPerformed
        setpanelaustralia();
        soundbagianbenua("benua-australia");
    }//GEN-LAST:event_btnaustraliaActionPerformed

    private void btneropaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneropaActionPerformed
        panelutama.nextPanel(20, worlderopa, panelutama.left);
        soundbagianbenua("benua-eropa");
    }//GEN-LAST:event_btneropaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainmenu a = new mainmenu();
        a.setVisible(true);
        this.dispose();
        this.a.stop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
panelutama.nextPanel(20, world, panelutama.left);        
    }//GEN-LAST:event_backActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
  panelutama.nextPanel(20, world, panelutama.left);  
    }//GEN-LAST:event_back1ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
  panelutama.nextPanel(20, world, panelutama.left);  
    }//GEN-LAST:event_back2ActionPerformed

    private void back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ActionPerformed
       panelutama.nextPanel(20, world, panelutama.left);  
    }//GEN-LAST:event_back3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void soundbagianbenua(String nama) {
        play a = new play();
        a.setnama(nama);
        a.start();
    }

    class play extends Thread {

        String nama;

        public void setnama(String nama) {
            this.nama = nama;
        }

        public void run() {
            try {
                FileInputStream fileInputStream = new FileInputStream("aset/bendera_jpg/sound_benua/" + nama + ".mp3");
                Player player = new Player(fileInputStream);
                System.out.println("Song is playing...");
                player.play();
                stop();
                System.out.println("aaaaa");
            } catch (FileNotFoundException e) {
            } catch (JavaLayerException e) {
            }
        }
    }
class playbacksound extends Thread {

        public void run() {
            try {
                FileInputStream fileInputStream = new FileInputStream("aset\\lagu\\bendera.mp3");
                Player player = new Player(fileInputStream);
                System.out.println("Song is playing...");
                player.play();
                System.out.println("aaaaa");
            } catch (JavaLayerException ex) {
                Logger.getLogger(tampil_planet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public void setpanelafrika(String lokasi) {
        String directory = "aset\\bendera_jpg\\afrika\\" + lokasi;

        soundbagianbenua(lokasi);
        tampil_bendera a = new tampil_bendera(directory);
        a.setVisible(true);
    }

    public void setpanelamerika(String lokasi) {
        String directory = "aset\\bendera_jpg\\amerika\\" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
    }

    public void setpanelasia(String lokasi) {
        String directory = "aset\\bendera_jpg\\asia\\" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
    }

    public void setpaneleropa(String lokasi) {
        String directory = "aset/bendera_jpg/eropa/" + lokasi;
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua(lokasi);
        a.setVisible(true);
    }

    public void setpanelaustralia() {
        String directory = "aset\\bendera_jpg\\australia";
        tampil_bendera a = new tampil_bendera(directory);
        soundbagianbenua("australia");
        a.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(negara_bendera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new negara_bendera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afrika;
    private javax.swing.JButton afrikabarat;
    private javax.swing.JButton afrikaselatan;
    private javax.swing.JButton afrikatengah;
    private javax.swing.JButton afrikatimur;
    private javax.swing.JButton afrikautara;
    private javax.swing.JLabel amerika;
    private javax.swing.JButton amerikaselatan;
    private javax.swing.JButton amerikatengah;
    private javax.swing.JButton amerikautara;
    private javax.swing.JLabel asia;
    private javax.swing.JButton asiabarat;
    private javax.swing.JButton asiaselatan;
    private javax.swing.JButton asiatengah;
    private javax.swing.JButton asiatenggara;
    private javax.swing.JButton asiatimur;
    private javax.swing.JLabel australia;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JButton back3;
    private javax.swing.JButton btnafrika;
    private javax.swing.JButton btnamerika;
    private javax.swing.JButton btnasia;
    private javax.swing.JButton btnaustralia;
    private javax.swing.JButton btneropa;
    private javax.swing.JLabel eropa;
    private javax.swing.JButton eropabarat;
    private javax.swing.JButton eropaselatan;
    private javax.swing.JButton eropatengah;
    private javax.swing.JButton eropatimur;
    private javax.swing.JButton eropautara;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelutama;
    private javax.swing.JPanel world;
    private javax.swing.JPanel worldafrika;
    private javax.swing.JPanel worldamerika;
    private javax.swing.JPanel worldasia;
    private javax.swing.JPanel worlderopa;
    // End of variables declaration//GEN-END:variables
}
